[package]
name = "adventofcode"
version = "0.1.0"
edition = "2021"
default-run = "adventofcode"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.26", features = ["derive"] }
regex = "1.7.0"
itertools = "0.10.5"
